### PR TITLE
update kendzi3d for Java 10+ and latest JOSM

### LINKED ISSUE #84: Update to JOSM 14005
Hello,
I removed [deprecated API](https://josm.openstreetmap.de/changeset/14005/josm/#file11) in 14005.
The plugin is impacted:
`kendzi3d=java.lang.NoSuchMethodError: kendzi.josm.jogl.JoglPlugin.getPluginDir()Ljava/lang/String;`

This is the method removed with javadoc:
```java
/*
* @return The directory for the plugin to store all kind of stuff.
* @deprecated (since 13007) to get the same directory as this method,  use {@code getPluginDirs().getUserDataDirectory(false)}.
* However, for files that can be characterized as cache or preferences, you are encouraged to use the appropriate
* {@link IBaseDirectories} method from {@link #getPluginDirs()}.
*/
@Deprecated
public String getPluginDir() {
    return new File(Main.pref.getPluginsDirectory(), info.name).getPath();
}
```

### PR DESCRIPTION
**Pull request by don-vip**
Fix #84 and https://josm.openstreetmap.de/ticket/16304

Not tested! I just ran "mvn verify" and checked all tests were OK.

### CODE REVIEW

**Comment by don-vip** [comment]
The plugin can now be compiled with Java 11. Can you please merge this PR?

**Comment by don-vip** [comment]
The plugin does not work anymore with JOSM latest.

**Comment by kendzi** [comment]
Ups, it is not compiling, looks like Main class was removed in latest josm?

**Comment by kendzi** [comment]
relised

**Comment by don-vip** [comment]
Thanks!

**Pull request merged**
